<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <!-- Deterministic output folder for delivery -->
    <BaseOutputPath>$(SolutionDir)build\bin\$(AssemblyName)\</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)$(Platform)\$(Configuration)\</OutputPath>
    <BaseIntermediateOutputPath>$(SolutionDir)build\obj\SaaCPsiHelloViewer</BaseIntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SaaCHelloWorld.Core\SaaCHelloWorld.Core.csproj" />
  </ItemGroup>
</Project>

